### ISSUE TITLE
Switch from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by embray** [lgpage/pytest-cython#12]
travis-ci.org is shutting down, so the repository needs to be re-registered but with travis-ci.com.  @lgpage I belive you will have to do this.

**Comment by lgpage** [comment]
@embray I think I have sorted this out and re-registered but with travis-ci.com

**Comment by embray** [comment]
Thank you!  I'll just wait until I make another PR and double-check that it's building there.

**Comment by embray** [comment]
Oops, it looks like the builds are still being run on travis-ci.org.

**Comment by lgpage** [comment]
Should be sorted now
