### ISSUE TITLE
pytest-8.0.0 breaks cython doctesting using this module

### ISSUE THREAD

**Issue by radhermit** [lgpage/pytest-cython#58]
**Describe the bug**
Running cython-based doctests using this module with the latest pytest release (8.0.0) fails.

See the following for the relevant error messages that are output when running a project's test suite under tox:

```
.tox/coverage/lib/python3.12/site-packages/pytest_cython/plugin.py:159: in collect
    optionflags = get_optionflags(self)
.tox/coverage/lib/python3.12/site-packages/_pytest/doctest.py:404: in get_optionflags
    optionflags_str = config.getini("doctest_optionflags")
E   AttributeError: 'DoctestModule' object has no attribute 'getini'
```

**Installed Packages**
The following Python and installed packages versions being used:

- Python: 3.11.7
- Cython: 3.0.8
- Pytest: 8.0.0
- Pytest-cython: 0.2.1

**Expected behavior**
The tests should run as expected.

**Comment by lpsinger** [comment]
Another thing that broke with pytest 8.x: the `path` argument was removed from the `pytest_collect_file` hook (see pytest-dev/pytest#11757). This causes the following error message:

```
pluggy._manager.PluginValidationError: Plugin 'pytest_cython' for hook 'pytest_collect_file'
hookimpl definition: pytest_collect_file(path, parent)
Argument(s) {'path'} are declared in the hookimpl but can not be found in the hookspec
```

See also healpy/healpy#912.
